### PR TITLE
Add `type: module` to package.json

### PR DESCRIPTION
**Pull request by aunumever**
Can't deploy to Netlify because package throws an error of not having `type: module` in package.json:

```
Dec 29, 11:07:56 AM: 6be0f3aa ERROR  (node:8) Warning: To load an ES module, set "type": "module" in the package.json or use the .mjs extension.
(Use `node --trace-warnings ...` to show where the warning was created)
Dec 29, 11:07:56 AM: 6be0f3aa ERROR  Unhandled Promise Rejection 	{"errorType":"Runtime.UnhandledPromiseRejection","errorMessage":"SyntaxError: Cannot use import statement outside a module","reason":{"errorType":"SyntaxError","errorMessage":"Cannot use import statement outside a module","stack":["/var/task/node_modules/svelte-carousel/src/main.js:1","import Carousel from './components/Carousel/Carousel.svelte'","^^^^^^","","SyntaxError: Cannot use import statement outside a module","    at Object.compileFunction (node:vm:352:18)","    at wrapSafe (node:internal/modules/cjs/loader:1033:15)","    at Module._compile (node:internal/modules/cjs/loader:1069:27)","    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)","    at Module.load (node:internal/modules/cjs/loader:981:32)","    at Function.Module._load (node:internal/modules/cjs/loader:822:12)","    at ModuleWrap.<anonymous> (node:internal/modules/esm/translators:163:29)","    at ModuleJob.run (node:internal/modules/esm/module_job:198:25)","    at async Promise.all (index 0)","    at async ESMLoader.import (node:internal/modules/esm/loader:385:24)"]},"promise":{},"stack":["Runtime.UnhandledPromiseRejection: SyntaxError: Cannot use import statement outside a module","    at process.<anonymous> (file:///var/runtime/index.mjs:1194:17)","    at process.emit (node:events:527:28)","    at emit (node:internal/process/promises:140:20)","    at processPromiseRejections (node:internal/process/promises:274:27)","    at processTicksAndRejections (node:internal/process/task_queues:97:32)"]}
Dec 29, 11:07:56 AM: Unknown application error occurred
Runtime.Unknown
Dec 29, 11:07:56 AM: 6be0f3aa Duration: 634.54 ms	Memory Usage: 58 MB
```

### CODE REVIEW

**Review by testvinder — APPROVED** [review]

**Comment by aunumever** [comment]
Can we add a version bump as well?

**Comment by jescalan** [comment]
Would love to see this one merged - it breaks compatibility with Vercel as well as Netlify it seems. Thank you for making this wonderful library!

**Comment by vadimkorr** [comment]
Ok, thank you guys
Could you please explain, why `type module` is important here?
Does it work well with csr ?

**Comment by MrTact** [comment]
>  Could you please explain, why type module is important here?

Without `type=module`, importing the component fails currently.

**Comment by icheered** [comment]
This breaks the build process when using Vite. Hopefully the maintainer sees this!

**Comment by icheered** [comment]
Bumping beause today I discovered that when running `vite build` the process fails due to the beforementioned reasons. @vadimkorr could you merge this PR please? @MrTact Do you know of a workaround until this is merged?

**Comment by vadimkorr** [comment]
Merged

svelte-carousel@1.0.21

**Comment by jescalan** [comment]
For anyone else following along, I have dug much deeper on this in an attempt to get this library to deploy to any of the main simple deployment platforms for svelte/sveltekit apps (netlify, vercel, etc), and I think the issue runs much deeper unfortunately. I was unable to get it successfully deployed even after sinking many, many hours into it. I went as far as [forking the library](https://github.com/jescalan/svelte-carousel) and making dramatic changes to the way that it is built and packaged (primarily using svelte-package, which I think should be the recommended path for a library like this), which helped quite a lot, but didn't resolve the issues entirely.

Ultimately, where I got it to, it was able to deploy and build successfully without breaking, which is much further than it gets trying to deploy straight from the published official version, but there was a persistent issue with css not being output correctly that caused it to be nonfunctional when deployed to Vercel, and Netlify just immediately shit the bed with a confusing error that didn't really make any sense. Ultimately, I ended up switching to using a different carousel library as I didn't really have any more hours to spare grappling with this.

I just want to mention that I am really thankful to @vadimkorr for building such a wonderful library, I was very sad to be put in a position to need to switch to something else, and I hope that others have better luck than I did at getting this into production!

**Comment by mattmarcello** [comment]
Has anyone made progress with this? 

Should this issue be re-opened? 

 When I import the Carousel component it breaks deploys on Vercel.  Works locally though.

**Comment by icheered** [comment]
AFAIK there has not been made progress because it would require to completely rewriting this (pretty awesome) package. The reason has to do with the package being written in javascript instead of typescript. The fix in 1.0.21 is only a workaround but doesn't really address the problem.

**Pull request merged**
