### PR TITLE
Fix missing export condition for svelte v4

### LINKED ISSUE #157: Warning when using svelte v4
When using svelte-carousel in combination with svelte v4, I'm getting the following warning.
```log
12:39:58 PM [vite-plugin-svelte] WARNING: The following packages have a svelte field in their package.json but no exports condition for svelte.

svelte-carousel@1.0.25

Please see https://github.com/sveltejs/vite-plugin-svelte/blob/main/docs/faq.md#missing-exports-condition for details.
```

### PR DESCRIPTION
**Pull request by Paultje52**
https://github.com/sveltejs/vite-plugin-svelte/blob/main/docs/faq.md#missing-exports-condition

Resolves #157

### CODE REVIEW

**Review by jis3r — APPROVED** [review]
I tested it locally, and it solves the warning without breaking the functionality.

**Comment by xxfogs** [comment]
When is it expected for this PR to get merged and new release be made?

**Review by oetiker — APPROVED** [review]

**Comment by Paultje52** [comment]
> When is it expected for this PR to get merged and new release be made?

It will probably take some time. There are PR’s open for more than half a year in this repo ☹️

**Comment by jalamprea** [comment]
Is there any reason to delete this PR without merging?

**Comment by darkwiz666** [comment]
"Some time" half the year is gone, can't someone message the man? lol

**Comment by jis3r** [comment]
@darkwiz666 I just thought about forking this repo and tackling all issues, but I think that the [Carousel-Component by shadcn-svelte](https://www.shadcn-svelte.com/docs/components/carousel) adresses the most relevant things, is up to date and the whole project is actively maintained

**Comment by xxfogs** [comment]
Another fine option is [splide](https://splidejs.com/)

**Pull request closed without merging**
