### PR TITLE
ADDED FEATURE: Responsiveness

### PR DESCRIPTION
**Pull request by TomDo1234**
Added a feature to allow for different particlesToShow at different screensizes

tested it in Storybook, it works.

### CODE REVIEW

**Comment by TomDo1234** [comment]
@vadimkorr 

There was a previous feature request on responsive option

**Comment by TomDo1234** [comment]
@vadimkorr Please chheck

**Comment by vadimkorr** [comment]
Hi @TomDo1234,
Thank you for your contribution.
I was thinking about this kind of feature, but in order not to overcomlicate the api I didn't implement it.
User can implement breakpoints outside of the component and provide particle props based on breakpoints, by himself.

**Comment by TomDo1234** [comment]
Thats fair, I still forked this just in case anybody needs it

**Comment by TomDo1234** [comment]
https://www.npmjs.com/package/@tomdo1234/svelte-carousel

**Pull request closed without merging**
